version: '3.8'

services:
  # Validator Node 1 (Alice)
  orium-validator-1:
    build:
      context: ../..
      dockerfile: docker/devnet/Dockerfile
    container_name: orium-validator-1
    ports:
      - "9944:9944"  # WebSocket RPC
      - "9933:9933"  # HTTP RPC
      - "30333:30333" # P2P
    volumes:
      - validator1-data:/data
    environment:
      - NODE_NAME=validator-1
      - VALIDATOR_KEY=alice
      - CHAIN_SPEC=dev
      - LOG_LEVEL=info
    command: [
      "/usr/local/bin/orium-node",
      "--alice",
      "--validator",
      "--base-path", "/data",
      "--chain", "dev",
      "--port", "30333",
      "--rpc-port", "9933",
      "--ws-port", "9944",
      "--rpc-cors", "all",
      "--unsafe-rpc-external",
      "--unsafe-ws-external",
      "--rpc-methods", "unsafe",
      "--log", "info,runtime::system=debug",
      "--bootnodes", "/dns/orium-validator-2/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp",
      "--prometheus-external",
      "--prometheus-port", "9615"
    ]
    networks:
      - orium-devnet
    restart: unless-stopped

  # Validator Node 2 (Bob)
  orium-validator-2:
    build:
      context: ../..
      dockerfile: docker/devnet/Dockerfile
    container_name: orium-validator-2
    ports:
      - "9945:9944"  # WebSocket RPC
      - "9934:9933"  # HTTP RPC
      - "30334:30333" # P2P
    volumes:
      - validator2-data:/data
    environment:
      - NODE_NAME=validator-2
      - VALIDATOR_KEY=bob
      - CHAIN_SPEC=dev
      - LOG_LEVEL=info
    command: [
      "/usr/local/bin/orium-node",
      "--bob",
      "--validator",
      "--base-path", "/data",
      "--chain", "dev",
      "--port", "30333",
      "--rpc-port", "9933",
      "--ws-port", "9944",
      "--rpc-cors", "all",
      "--unsafe-rpc-external",
      "--unsafe-ws-external",
      "--rpc-methods", "unsafe",
      "--log", "info,runtime::system=debug",
      "--bootnodes", "/dns/orium-validator-1/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD",
      "--prometheus-external",
      "--prometheus-port", "9615"
    ]
    networks:
      - orium-devnet
    restart: unless-stopped

  # Validator Node 3 (Charlie)
  orium-validator-3:
    build:
      context: ../..
      dockerfile: docker/devnet/Dockerfile
    container_name: orium-validator-3
    ports:
      - "9946:9944"  # WebSocket RPC
      - "9935:9933"  # HTTP RPC
      - "30335:30333" # P2P
    volumes:
      - validator3-data:/data
    environment:
      - NODE_NAME=validator-3
      - VALIDATOR_KEY=charlie
      - CHAIN_SPEC=dev
      - LOG_LEVEL=info
    command: [
      "/usr/local/bin/orium-node",
      "--charlie",
      "--validator",
      "--base-path", "/data",
      "--chain", "dev",
      "--port", "30333",
      "--rpc-port", "9933",
      "--ws-port", "9944",
      "--rpc-cors", "all",
      "--unsafe-rpc-external",
      "--unsafe-ws-external",
      "--rpc-methods", "unsafe",
      "--log", "info,runtime::system=debug",
      "--bootnodes", "/dns/orium-validator-1/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD",
      "--prometheus-external",
      "--prometheus-port", "9615"
    ]
    networks:
      - orium-devnet
    restart: unless-stopped

  # Validator Node 4 (Dave)
  orium-validator-4:
    build:
      context: ../..
      dockerfile: docker/devnet/Dockerfile
    container_name: orium-validator-4
    ports:
      - "9947:9944"  # WebSocket RPC
      - "9936:9933"  # HTTP RPC
      - "30336:30333" # P2P
    volumes:
      - validator4-data:/data
    environment:
      - NODE_NAME=validator-4
      - VALIDATOR_KEY=dave
      - CHAIN_SPEC=dev
      - LOG_LEVEL=info
    command: [
      "/usr/local/bin/orium-node",
      "--dave",
      "--validator",
      "--base-path", "/data",
      "--chain", "dev",
      "--port", "30333",
      "--rpc-port", "9933",
      "--ws-port", "9944",
      "--rpc-cors", "all",
      "--unsafe-rpc-external",
      "--unsafe-ws-external",
      "--rpc-methods", "unsafe",
      "--log", "info,runtime::system=debug",
      "--bootnodes", "/dns/orium-validator-1/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD",
      "--prometheus-external",
      "--prometheus-port", "9615"
    ]
    networks:
      - orium-devnet
    restart: unless-stopped

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: orium-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - orium-devnet
    restart: unless-stopped

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: orium-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - orium-devnet
    restart: unless-stopped

networks:
  orium-devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  validator1-data:
  validator2-data:
  validator3-data:
  validator4-data:
  prometheus-data:
  grafana-data:
