global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'orium-validators'
    static_configs:
      - targets: 
        - 'orium-validator-1:9615'
        - 'orium-validator-2:9615'
        - 'orium-validator-3:9615'
        - 'orium-validator-4:9615'
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
